# -*- coding: utf-8 -*-
# @@@LICENSE
#
# Copyright (c) 2014 LG Electronics, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# LICENSE@@@
#
# Based information from: http://www.timeanddate.com/library/abbreviations/timezones/

abbrevs = {
u"ACDT": u"Australian Central Daylight Time",
u"ACST": u"Australian Central Standard Time",
u"ACT": u"ASEAN Common Time",
u"ADT": u"Atlantic Daylight Time",
u"AEDT": u"Australian Eastern Daylight Time",
u"AEST": u"Australian Eastern Standard Time",
u"AFT": u"Afghanistan Time",
u"AKDT": u"Alaska Daylight Time",
u"AKST": u"Alaska Standard Time",
u"AMST": u"Amazon Summer Time (Brazil)",
u"AMST": u"Armenia Summer Time",
u"AMT": u"Amazon Time (Brazil)",
u"AMT": u"Armenia Time",
u"ART": u"Argentina Time",
u"AST": u"Arabia Standard Time",
u"AST": u"Atlantic Standard Time",
u"AWDT": u"Australian Western Daylight Time",
u"AWST": u"Australian Western Standard Time",
u"AZOST": u"Azores Standard Time",
u"AZT": u"Azerbaijan Time",
u"BDT": u"Brunei Time",
u"BIOT": u"British Indian Ocean Time",
u"BIT": u"Baker Island Time",
u"BOT": u"Bolivia Time",
u"BRT": u"Brasilia Time",
u"BST": u"Bangladesh Standard Time",
#"BST": u"British Summer Time (British Standard Time from Feb 1968 to Oct 1971)",
u"BTT": u"Bhutan Time",
u"CAT": u"Central Africa Time",
u"CCT": u"Cocos Islands Time",
u"CDT": u"Central Daylight Time (North America)",
u"CDT": u"Cuba Daylight Time",
u"CEDT": u"Central European Daylight Time",
u"CEST": u"Central European Summer Time (Cf. HAEC)",
u"CET": u"Central European Time",
u"CHADT": u"Chatham Daylight Time",
u"CHAST": u"Chatham Standard Time",
u"CHOT": u"Choibalsan",
u"ChST": u"Chamorro Standard Time",
u"CHUT": u"Chuuk Time",
u"CIST": u"Clipperton Island Standard Time",
u"CIT": u"Central Indonesia Time",
u"CKT": u"Cook Island Time",
u"CLST": u"Chile Summer Time",
u"CLT": u"Chile Standard Time",
u"COST": u"Colombia Summer Time",
u"COT": u"Colombia Time",
u"CST": u"Central Standard Time (North America)",
u"CST": u"China Standard Time",
u"CST": u"Central Standard Time (Australia)",
u"CST": u"Central Summer Time (Australia)",
u"CST": u"Cuba Standard Time",
u"CT": u"China time",
u"CVT": u"Cape Verde Time",
u"CWST": u"Central Western Standard Time (Australia) unofficial",
u"CXT": u"Christmas Island Time",
u"DAVT": u"Davis Time",
u"DDUT": u"Dumont d'Urville Time",
u"DFT": u"AIX specific equivalent of Central European Time",
u"EASST": u"Easter Island Standard Summer Time",
u"EAST": u"Easter Island Standard Time",
u"EAT": u"East Africa Time",
u"ECT": u"Eastern Caribbean Time (does not recognise DST)",
u"ECT": u"Ecuador Time",
u"EDT": u"Eastern Daylight Time (North America)",
u"EEDT": u"Eastern European Daylight Time",
u"EEST": u"Eastern European Summer Time",
u"EET": u"Eastern European Time",
u"EGST": u"Eastern Greenland Summer Time",
u"EGT": u"Eastern Greenland Time",
u"EIT": u"Eastern Indonesian Time",
u"EST": u"Eastern Standard Time (North America)",
u"EST": u"Eastern Standard Time (Australia)",
u"FET": u"Further-eastern European Time",
u"FJT": u"Fiji Time",
u"FKST": u"Falkland Islands Standard Time",
u"FKST": u"Falkland Islands Summer Time",
u"FKT": u"Falkland Islands Time",
u"FNT": u"Fernando de Noronha Time",
u"GALT": u"Galapagos Time",
u"GAMT": u"Gambier Islands",
u"GET": u"Georgia Standard Time",
u"GFT": u"French Guiana Time",
u"GILT": u"Gilbert Island Time",
u"GIT": u"Gambier Island Time",
u"GMT": u"Greenwich Mean Time",
u"GST": u"South Georgia and the South Sandwich Islands",
u"GST": u"Gulf Standard Time",
u"GYT": u"Guyana Time",
u"HADT": u"Hawaii-Aleutian Daylight Time",
u"HAEC": u"Heure Avancée d'Europe Centrale francised name for CEST",
u"HAST": u"Hawaii-Aleutian Standard Time",
u"HKT": u"Hong Kong Time",
u"HMT": u"Heard and McDonald Islands Time",
u"HOVT": u"Khovd Time",
u"HST": u"Hawaii Standard Time",
u"ICT": u"Indochina Time",
u"IDT": u"Israel Daylight Time",
u"IOT": u"Indian Ocean Time",
u"IRDT": u"Iran Daylight Time",
u"IRKT": u"Irkutsk Time",
u"IRST": u"Iran Standard Time",
u"IST": u"Indian Standard Time",
u"IST": u"Irish Standard Time",
u"IST": u"Israel Standard Time",
u"JST": u"Japan Standard Time",
u"KGT": u"Kyrgyzstan time",
u"KOST": u"Kosrae Time",
u"KRAT": u"Krasnoyarsk Time",
u"KST": u"Korea Standard Time",
u"LHST": u"Lord Howe Standard Time",
u"LHST": u"Lord Howe Summer Time",
u"LINT": u"Line Islands Time",
u"MAGT": u"Magadan Time",
u"MART": u"Marquesas Islands Time",
u"MAWT": u"Mawson Station Time",
u"MDT": u"Mountain Daylight Time (North America)",
u"MET": u"Middle European Time Same zone as CET",
u"MEST": u"Middle European Saving Time Same zone as CEST",
u"MHT": u"Marshall Islands",
u"MIST": u"Macquarie Island Station Time",
u"MIT": u"Marquesas Islands Time",
u"MMT": u"Myanmar Time",
u"MSK": u"Moscow Time",
u"MST": u"Malaysia Standard Time",
u"MST": u"Mountain Standard Time (North America)",
u"MST": u"Myanmar Standard Time",
u"MUT": u"Mauritius Time",
u"MVT": u"Maldives Time",
u"MYT": u"Malaysia Time",
u"NCT": u"New Caledonia Time",
u"NDT": u"Newfoundland Daylight Time",
u"NFT": u"Norfolk Time",
u"NPT": u"Nepal Time",
u"NST": u"Newfoundland Standard Time",
u"NT": u"Newfoundland Time",
u"NUT": u"Niue Time",
u"NZDT": u"New Zealand Daylight Time",
u"NZST": u"New Zealand Standard Time",
u"OMST": u"Omsk Time",
u"ORAT": u"Oral Time",
u"PDT": u"Pacific Daylight Time (North America)",
u"PET": u"Peru Time",
u"PETT": u"Kamchatka Time",
u"PGT": u"Papua New Guinea Time",
u"PHOT": u"Phoenix Island Time",
u"PHT": u"Philippine Time",
u"PKT": u"Pakistan Standard Time",
u"PMDT": u"Saint Pierre and Miquelon Daylight time",
u"PMST": u"Saint Pierre and Miquelon Standard Time",
u"PONT": u"Pohnpei Standard Time",
u"PST": u"Pacific Standard Time (North America)",
u"PYST": u"Paraguay Summer Time (South America)",
u"PYT": u"Paraguay Time (South America)",
u"RET": u"Réunion Time",
u"ROTT": u"Rothera Research Station Time",
u"SAKT": u"Sakhalin Island time",
u"SAMT": u"Samara Time",
u"SAST": u"South African Standard Time",
u"SBT": u"Solomon Islands Time",
u"SCT": u"Seychelles Time",
u"SGT": u"Singapore Time",
u"SLST": u"Sri Lanka Time",
u"SRT": u"Suriname Time",
u"SST": u"Samoa Standard Time",
u"SST": u"Singapore Standard Time",
u"SYOT": u"Showa Station Time",
u"TAHT": u"Tahiti Time",
u"THA": u"Thailand Standard Time",
u"TFT": u"Indian/Kerguelen",
u"TJT": u"Tajikistan Time",
u"TKT": u"Tokelau Time",
u"TLT": u"Timor Leste Time",
u"TMT": u"Turkmenistan Time",
u"TOT": u"Tonga Time",
u"TVT": u"Tuvalu Time",
u"UCT": u"Coordinated Universal Time",
u"ULAT": u"Ulaanbaatar Time",
u"UYST": u"Uruguay Summer Time",
u"UYT": u"Uruguay Standard Time",
u"UZT": u"Uzbekistan Time",
u"VET": u"Venezuelan Standard Time",
u"VLAT": u"Vladivostok Time",
u"VOLT": u"Volgograd Time",
u"VOST": u"Vostok Station Time",
u"VUT": u"Vanuatu Time",
u"WAKT": u"Wake Island Time",
u"WAST": u"West Africa Summer Time",
u"WAT": u"West Africa Time",
u"WEDT": u"Western European Daylight Time",
u"WEST": u"Western European Summer Time",
u"WET": u"Western European Time",
u"WST": u"Western Standard Time",
u"YAKT": u"Yakutsk Time",
u"YEKT": u"Yekaterinburg Time",
u"Z": u"Zulu Time (Coordinated Universal Time)"
}
